spring:
  application:
    name: task-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/task_scheduler
    username: scheduler
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
